# Generated by Django 5.2.3 on 2026-06-30 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dob", models.DateField()),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("aadhaar_number", models.CharField(max_length=12)),
                ("license_number", models.CharField(max_length=30)),
                ("license_expiry", models.DateField()),
                ("experience", models.PositiveIntegerField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="drivers/"),
                ),
                (
                    "license_copy",
                    models.ImageField(blank=True, null=True, upload_to="licenses/"),
                ),
                (
                    "aadhaar_copy",
                    models.ImageField(blank=True, null=True, upload_to="aadhaar/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicle.vehicle",
                    ),
                ),
            ],
        ),
    ]
