# Generated by Django 5.2.16 on 2026-07-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='insurance_copy',
            field=models.ImageField(blank=True, null=True, upload_to='insurance/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='rc_copy',
            field=models.ImageField(blank=True, null=True, upload_to='rc/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
    ]
