# Generated by Django 5.2.16 on 2026-07-29 14:10

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_razorpay_order_id_payment_razorpay_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='category',
            field=models.CharField(choices=[('TOPUP', 'Wallet Top-Up'), ('RIDE_PAYMENT', 'Ride Booking Payment'), ('DRIVER_EARNINGS', 'Driver Trip Earnings'), ('WITHDRAWAL', 'Bank Account Withdrawal'), ('REFUND', 'Trip Refund')], default='TOPUP', max_length=30),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='txn_reference_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('CREDIT', 'Credit (+)'), ('DEBIT', 'Debit (-)')], max_length=10),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_holder', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, default='State Bank of India', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('PROCESSED', 'Processed to Bank'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
