# Generated by Django 5.2.16 on 2026-07-22 17:19

import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('heading', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Driver Location',
                'verbose_name_plural': 'Driver Locations',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='RideLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('DRIVER_SEARCH', 'Searching Driver'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_COMING', 'Driver En Route'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('OTP_VERIFIED', 'OTP Verified'), ('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PAYMENT_DONE', 'Payment Done'), ('DRIVER_REJECTED', 'Driver Rejected Ride'), ('TIMEOUT', 'Request Timed Out')], max_length=30)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ride Log',
                'verbose_name_plural': 'Ride Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
