# Generated by Django 5.2.17 on 2026-09-20 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('AUTO', 'Auto / Rickshaw'), ('MINI', 'Mini'), ('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('LUXURY', 'Luxury'), ('PREMIUM', 'Premium')], max_length=20),
        ),
    ]
