# Generated by Django 5.2.16 on 2026-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(default='MINI', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('SEARCHING_DRIVER', 'Searching Driver'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_COMING', 'Driver En Route'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('CANCELLED', 'Cancelled'), ('NO_DRIVER_FOUND', 'No Driver Found'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On Ride', 'On Ride'), ('Completed', 'Completed')], default='SEARCHING_DRIVER', max_length=30),
        ),
    ]
