# Generated by Django 5.2.16 on 2026-07-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_coupon_pricingrule_booking_airport_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rating_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
