# Generated by Django 5.2.16 on 2026-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_share_token_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_category',
            field=models.CharField(choices=[('DAILY_RIDE', 'Daily Ride'), ('SCHEDULED', 'Book Later (Scheduled)'), ('RENTAL', 'Hourly Rental'), ('OUTSTATION', 'Outstation Cab')], default='DAILY_RIDE', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='outstation_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_package',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
