# Generated by Django 5.2.16 on 2026-08-01 05:07

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_waypoints_json_faresplit_favoritedriver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash Payment'), ('WALLET', 'Rovexa Wallet'), ('ONLINE', 'Online Payment / UPI')], default='CASH', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('AUTO', 'Rovexa Auto (3 Seats)'), ('MINI', 'Rovexa Mini (4 Seats)'), ('SEDAN', 'Rovexa Sedan (4 Seats)'), ('SUV', 'Rovexa SUV (6 Seats)'), ('PREMIUM', 'Rovexa Premium (4 Seats)')], default='MINI', max_length=50),
        ),
        migrations.CreateModel(
            name='RideChatMessage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='CUSTOMER', max_length=20)),
                ('sender_name', models.CharField(default='User', max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='booking.booking')),
            ],
        ),
    ]
