# Generated by Django 5.2.16 on 2026-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
