# Generated by Django 5.2.17 on 2026-09-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_driver_notes_booking_passenger_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('ACCEPTED', 'Accepted by Admin'), ('REJECTED', 'Rejected by Admin'), ('TRIP_STARTED', 'Trip Started'), ('TRIP_COMPLETED', 'Trip Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
    ]
